package Vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author aaron
 */
public class MenuInicio2_0 extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicio2_0
     */
    public MenuInicio2_0() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        Panel1MenuInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Panel2MenuInicio = new javax.swing.JPanel();
        lblVentas = new javax.swing.JLabel();
        lblInventario = new javax.swing.JLabel();
        lblDirectorio = new javax.swing.JLabel();
        lblProvServiciosInternet = new javax.swing.JLabel();
        lblRegistroLlamadas = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        btnReportes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JLabel();
        Escritorio = new javax.swing.JDesktopPane();
        lblCasosSoporte = new javax.swing.JPanel();
        btnCasosSoporte = new javax.swing.JLabel();
        lblMotivoSoporte = new javax.swing.JPanel();
        btnMotivosSoporte = new javax.swing.JLabel();
        lblItems = new javax.swing.JPanel();
        btnMateriales = new javax.swing.JLabel();
        lbltipoCliente = new javax.swing.JPanel();
        btnSuspension = new javax.swing.JLabel();
        lblTarifaInstalacion = new javax.swing.JPanel();
        btnPlaneInternet = new javax.swing.JLabel();
        lblFactura = new javax.swing.JPanel();
        btnFacturas = new javax.swing.JLabel();
        lblContribuyentes = new javax.swing.JPanel();
        btnContribuyentes = new javax.swing.JLabel();
        lbltipoContratos = new javax.swing.JPanel();
        btnContratos = new javax.swing.JLabel();
        lbltipoOrdenes = new javax.swing.JPanel();
        btnOrdenesTrabajo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel1MenuInicio.setBackground(new java.awt.Color(153, 0, 0));
        Panel1MenuInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("AIROSRED");
        Panel1MenuInicio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 6, -1, -1));

        lblNombreUsuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreUsuario.setText("----------------------------");
        Panel1MenuInicio.add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText(" |");
        Panel1MenuInicio.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 30, -1));

        lblCedula.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCedula.setForeground(new java.awt.Color(0, 0, 0));
        lblCedula.setText("----------------------------");
        Panel1MenuInicio.add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/icons8-usuario-masculino-en-círculo-45.png"))); // NOI18N
        Panel1MenuInicio.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, -1, -1));

        jDesktopPane1.add(Panel1MenuInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1310, 70));

        Panel2MenuInicio.setBackground(new java.awt.Color(255, 51, 51));
        Panel2MenuInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVentas.setForeground(new java.awt.Color(0, 0, 0));
        lblVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/icons8-vender-stock-20.png"))); // NOI18N
        lblVentas.setText("Ventas");
        Panel2MenuInicio.add(lblVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 80, 58));

        lblInventario.setForeground(new java.awt.Color(0, 0, 0));
        lblInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/icons8-caja-de-herramientas-20.png"))); // NOI18N
        lblInventario.setText("Inventario");
        Panel2MenuInicio.add(lblInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 100, 60));

        lblDirectorio.setForeground(new java.awt.Color(0, 0, 0));
        lblDirectorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/icons8-libros-20.png"))); // NOI18N
        lblDirectorio.setText("Directorio");
        Panel2MenuInicio.add(lblDirectorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 90, 60));

        lblProvServiciosInternet.setForeground(new java.awt.Color(0, 0, 0));
        lblProvServiciosInternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/icons8-wifi-20.png"))); // NOI18N
        lblProvServiciosInternet.setText("Prov. Servicios de Internet");
        Panel2MenuInicio.add(lblProvServiciosInternet, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 190, 60));

        lblRegistroLlamadas.setForeground(new java.awt.Color(0, 0, 0));
        lblRegistroLlamadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/icons8-auriculares-20.png"))); // NOI18N
        lblRegistroLlamadas.setText("Registro de llamadas");
        Panel2MenuInicio.add(lblRegistroLlamadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 170, 60));

        lblInicio.setForeground(new java.awt.Color(0, 0, 0));
        lblInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/icons8-casa-20.png"))); // NOI18N
        lblInicio.setText("Inicio");
        Panel2MenuInicio.add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 60));

        btnReportes.setBackground(new java.awt.Color(0, 0, 0));
        btnReportes.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(0, 0, 0));
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/IconosSubMenu/icons8-libro-20.png"))); // NOI18N
        btnReportes.setText("Reportes");
        Panel2MenuInicio.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 140, 60));

        jDesktopPane1.add(Panel2MenuInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1310, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/icons8-cerrar-ventana-20 (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1284, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir))
        );

        jDesktopPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 20));

        Escritorio.setBackground(new java.awt.Color(255, 255, 255));
        Escritorio.setForeground(new java.awt.Color(255, 102, 102));

        lblCasosSoporte.setBackground(new java.awt.Color(255, 102, 102));
        lblCasosSoporte.setForeground(new java.awt.Color(255, 255, 255));

        btnCasosSoporte.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnCasosSoporte.setForeground(new java.awt.Color(0, 0, 0));
        btnCasosSoporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/IconosSubMenu/icons8-auriculares-20 (1).png"))); // NOI18N
        btnCasosSoporte.setText("Casos de Soporte");

        javax.swing.GroupLayout lblCasosSoporteLayout = new javax.swing.GroupLayout(lblCasosSoporte);
        lblCasosSoporte.setLayout(lblCasosSoporteLayout);
        lblCasosSoporteLayout.setHorizontalGroup(
            lblCasosSoporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblCasosSoporteLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(btnCasosSoporte, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        lblCasosSoporteLayout.setVerticalGroup(
            lblCasosSoporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCasosSoporte, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        Escritorio.add(lblCasosSoporte);
        lblCasosSoporte.setBounds(550, 0, 170, 39);

        lblMotivoSoporte.setBackground(new java.awt.Color(255, 102, 102));
        lblMotivoSoporte.setForeground(new java.awt.Color(255, 255, 255));

        btnMotivosSoporte.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnMotivosSoporte.setForeground(new java.awt.Color(0, 0, 0));
        btnMotivosSoporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/IconosSubMenu/icons8-llamar-a-hombre-20.png"))); // NOI18N
        btnMotivosSoporte.setText("Motivos de soporte");

        javax.swing.GroupLayout lblMotivoSoporteLayout = new javax.swing.GroupLayout(lblMotivoSoporte);
        lblMotivoSoporte.setLayout(lblMotivoSoporteLayout);
        lblMotivoSoporteLayout.setHorizontalGroup(
            lblMotivoSoporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblMotivoSoporteLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(btnMotivosSoporte)
                .addContainerGap())
        );
        lblMotivoSoporteLayout.setVerticalGroup(
            lblMotivoSoporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMotivosSoporte, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        Escritorio.add(lblMotivoSoporte);
        lblMotivoSoporte.setBounds(550, 40, 170, 39);

        lblItems.setBackground(new java.awt.Color(255, 102, 102));
        lblItems.setForeground(new java.awt.Color(255, 255, 255));

        btnMateriales.setBackground(new java.awt.Color(0, 0, 0));
        btnMateriales.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnMateriales.setForeground(new java.awt.Color(0, 0, 0));
        btnMateriales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/IconosSubMenu/icons8-categorizar-20.png"))); // NOI18N
        btnMateriales.setText("Materiales");

        javax.swing.GroupLayout lblItemsLayout = new javax.swing.GroupLayout(lblItems);
        lblItems.setLayout(lblItemsLayout);
        lblItemsLayout.setHorizontalGroup(
            lblItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblItemsLayout.createSequentialGroup()
                .addComponent(btnMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );
        lblItemsLayout.setVerticalGroup(
            lblItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMateriales, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Escritorio.add(lblItems);
        lblItems.setBounds(260, 0, 120, 40);

        lbltipoCliente.setBackground(new java.awt.Color(255, 102, 102));
        lbltipoCliente.setForeground(new java.awt.Color(255, 255, 255));

        btnSuspension.setBackground(new java.awt.Color(0, 0, 0));
        btnSuspension.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnSuspension.setForeground(new java.awt.Color(0, 0, 0));
        btnSuspension.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/IconosSubMenu/icons8-cancelar-20.png"))); // NOI18N
        btnSuspension.setText("Suspension ");

        javax.swing.GroupLayout lbltipoClienteLayout = new javax.swing.GroupLayout(lbltipoCliente);
        lbltipoCliente.setLayout(lbltipoClienteLayout);
        lbltipoClienteLayout.setHorizontalGroup(
            lbltipoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbltipoClienteLayout.createSequentialGroup()
                .addComponent(btnSuspension, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        lbltipoClienteLayout.setVerticalGroup(
            lbltipoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbltipoClienteLayout.createSequentialGroup()
                .addComponent(btnSuspension, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        Escritorio.add(lbltipoCliente);
        lbltipoCliente.setBounds(370, 40, 190, 30);

        lblTarifaInstalacion.setBackground(new java.awt.Color(255, 102, 102));
        lblTarifaInstalacion.setForeground(new java.awt.Color(255, 255, 255));

        btnPlaneInternet.setBackground(new java.awt.Color(0, 0, 0));
        btnPlaneInternet.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnPlaneInternet.setForeground(new java.awt.Color(0, 0, 0));
        btnPlaneInternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/IconosSubMenu/icons8-libro-20.png"))); // NOI18N
        btnPlaneInternet.setText("Planes de Internet");

        javax.swing.GroupLayout lblTarifaInstalacionLayout = new javax.swing.GroupLayout(lblTarifaInstalacion);
        lblTarifaInstalacion.setLayout(lblTarifaInstalacionLayout);
        lblTarifaInstalacionLayout.setHorizontalGroup(
            lblTarifaInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblTarifaInstalacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPlaneInternet, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );
        lblTarifaInstalacionLayout.setVerticalGroup(
            lblTarifaInstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblTarifaInstalacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPlaneInternet, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        Escritorio.add(lblTarifaInstalacion);
        lblTarifaInstalacion.setBounds(360, 0, 190, 40);

        lblFactura.setBackground(new java.awt.Color(255, 102, 102));
        lblFactura.setForeground(new java.awt.Color(255, 255, 255));

        btnFacturas.setBackground(new java.awt.Color(0, 0, 0));
        btnFacturas.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnFacturas.setForeground(new java.awt.Color(0, 0, 0));
        btnFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/IconosSubMenu/icons8-factura-20.png"))); // NOI18N
        btnFacturas.setText("Facturas");

        javax.swing.GroupLayout lblFacturaLayout = new javax.swing.GroupLayout(lblFactura);
        lblFactura.setLayout(lblFacturaLayout);
        lblFacturaLayout.setHorizontalGroup(
            lblFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        lblFacturaLayout.setVerticalGroup(
            lblFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        Escritorio.add(lblFactura);
        lblFactura.setBounds(80, 0, 90, 39);

        lblContribuyentes.setBackground(new java.awt.Color(255, 102, 102));
        lblContribuyentes.setForeground(new java.awt.Color(255, 255, 255));

        btnContribuyentes.setBackground(new java.awt.Color(0, 0, 0));
        btnContribuyentes.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnContribuyentes.setForeground(new java.awt.Color(0, 0, 0));
        btnContribuyentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/IconosSubMenu/icons8-alinear-centro-de-contenido-de-la-célula-20.png"))); // NOI18N
        btnContribuyentes.setText("Contribuyentes");

        javax.swing.GroupLayout lblContribuyentesLayout = new javax.swing.GroupLayout(lblContribuyentes);
        lblContribuyentes.setLayout(lblContribuyentesLayout);
        lblContribuyentesLayout.setHorizontalGroup(
            lblContribuyentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblContribuyentesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnContribuyentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        lblContribuyentesLayout.setVerticalGroup(
            lblContribuyentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnContribuyentes, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Escritorio.add(lblContribuyentes);
        lblContribuyentes.setBounds(170, 0, 140, 40);

        lbltipoContratos.setBackground(new java.awt.Color(255, 102, 102));
        lbltipoContratos.setForeground(new java.awt.Color(255, 255, 255));

        btnContratos.setBackground(new java.awt.Color(0, 0, 0));
        btnContratos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnContratos.setForeground(new java.awt.Color(0, 0, 0));
        btnContratos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/IconosSubMenu/icons8-contrato-de-trabajo-20.png"))); // NOI18N
        btnContratos.setText("Contratos");

        javax.swing.GroupLayout lbltipoContratosLayout = new javax.swing.GroupLayout(lbltipoContratos);
        lbltipoContratos.setLayout(lbltipoContratosLayout);
        lbltipoContratosLayout.setHorizontalGroup(
            lbltipoContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbltipoContratosLayout.createSequentialGroup()
                .addComponent(btnContratos, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        lbltipoContratosLayout.setVerticalGroup(
            lbltipoContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbltipoContratosLayout.createSequentialGroup()
                .addComponent(btnContratos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        Escritorio.add(lbltipoContratos);
        lbltipoContratos.setBounds(370, 70, 180, 50);

        lbltipoOrdenes.setBackground(new java.awt.Color(255, 102, 102));
        lbltipoOrdenes.setForeground(new java.awt.Color(255, 255, 255));

        btnOrdenesTrabajo.setBackground(new java.awt.Color(0, 0, 0));
        btnOrdenesTrabajo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnOrdenesTrabajo.setForeground(new java.awt.Color(0, 0, 0));
        btnOrdenesTrabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/IconosSubMenu/icons8-carpeta-20.png"))); // NOI18N
        btnOrdenesTrabajo.setText("Ordenes de Trabajo");

        javax.swing.GroupLayout lbltipoOrdenesLayout = new javax.swing.GroupLayout(lbltipoOrdenes);
        lbltipoOrdenes.setLayout(lbltipoOrdenesLayout);
        lbltipoOrdenesLayout.setHorizontalGroup(
            lbltipoOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbltipoOrdenesLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(btnOrdenesTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        lbltipoOrdenesLayout.setVerticalGroup(
            lbltipoOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbltipoOrdenesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOrdenesTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        Escritorio.add(lbltipoOrdenes);
        lbltipoOrdenes.setBounds(370, 120, 180, 50);

        jDesktopPane1.add(Escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1300, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1301, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getLbltipoContratos() {
        return lbltipoContratos;
    }

    public void setLbltipoContratos(JPanel lbltipoContratos) {
        this.lbltipoContratos = lbltipoContratos;
    }

    public JPanel getLbltipoOrdenes() {
        return lbltipoOrdenes;
    }

    public void setLbltipoOrdenes(JPanel lbltipoOrdenes) {
        this.lbltipoOrdenes = lbltipoOrdenes;
    }

    public JLabel getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JLabel btnSalir) {
        this.btnSalir = btnSalir;
    }

    public JDesktopPane getEscritorio() {
        return Escritorio;
    }

    public void setEscritorio(JDesktopPane Escritorio) {
        this.Escritorio = Escritorio;
    }

    public JPanel getPanel1MenuInicio() {
        return Panel1MenuInicio;
    }

    public void setPanel1MenuInicio(JPanel Panel1MenuInicio) {
        this.Panel1MenuInicio = Panel1MenuInicio;
    }

    public JPanel getPanel2MenuInicio() {
        return Panel2MenuInicio;
    }

    public void setPanel2MenuInicio(JPanel Panel2MenuInicio) {
        this.Panel2MenuInicio = Panel2MenuInicio;
    }

    public JLabel getBtnCasosSoporte() {
        return btnCasosSoporte;
    }

    public void setBtnCasosSoporte(JLabel btnCasosSoporte) {
        this.btnCasosSoporte = btnCasosSoporte;
    }

    public JLabel getBtnContratos() {
        return btnContratos;
    }

    public void setBtnContratos(JLabel btnContratos) {
        this.btnContratos = btnContratos;
    }

    public JLabel getBtnContribuyentes() {
        return btnContribuyentes;
    }

    public void setBtnContribuyentes(JLabel btnContribuyentes) {
        this.btnContribuyentes = btnContribuyentes;
    }

    public JLabel getBtnFacturas() {
        return btnFacturas;
    }

    public void setBtnFacturas(JLabel btnFacturas) {
        this.btnFacturas = btnFacturas;
    }

    public JLabel getBtnItems() {
        return btnMateriales;
    }

    public void setBtnItems(JLabel btnItems) {
        this.btnMateriales = btnItems;
    }

    public JLabel getBtnMotivosSoporte() {
        return btnMotivosSoporte;
    }

    public void setBtnMotivosSoporte(JLabel btnMotivosSoporte) {
        this.btnMotivosSoporte = btnMotivosSoporte;
    }

    public JLabel getBtnOrdenesTrabajo() {
        return btnOrdenesTrabajo;
    }

    public void setBtnOrdenesTrabajo(JLabel btnOrdenesTrabajo) {
        this.btnOrdenesTrabajo = btnOrdenesTrabajo;
    }

    public JLabel getBtnPlaneInternet() {
        return btnPlaneInternet;
    }

    public void setBtnPlaneInternet(JLabel btnPlaneInternet) {
        this.btnPlaneInternet = btnPlaneInternet;
    }

    public JLabel getBtnReportes() {
        return btnReportes;
    }

    public void setBtnReportes(JLabel btnReportes) {
        this.btnReportes = btnReportes;
    }

    public JLabel getBtnSuspension() {
        return btnSuspension;
    }

    public void setBtnSuspension(JLabel btnSuspension) {
        this.btnSuspension = btnSuspension;
    }

    public JDesktopPane getjDesktopPane1() {
        return jDesktopPane1;
    }

    public void setjDesktopPane1(JDesktopPane jDesktopPane1) {
        this.jDesktopPane1 = jDesktopPane1;
    }

    public JPanel getLblCasosSoporte() {
        return lblCasosSoporte;
    }

    public void setLblCasosSoporte(JPanel lblCasosSoporte) {
        this.lblCasosSoporte = lblCasosSoporte;
    }

    public JLabel getLblCedula() {
        return lblCedula;
    }

    public void setLblCedula(JLabel lblCedula) {
        this.lblCedula = lblCedula;
    }

    public JPanel getLblContribuyentes() {
        return lblContribuyentes;
    }

    public void setLblContribuyentes(JPanel lblContribuyentes) {
        this.lblContribuyentes = lblContribuyentes;
    }

    public JLabel getLblDirectorio() {
        return lblDirectorio;
    }

    public void setLblDirectorio(JLabel lblDirectorio) {
        this.lblDirectorio = lblDirectorio;
    }

    public JPanel getLblFactura() {
        return lblFactura;
    }

    public void setLblFactura(JPanel lblFactura) {
        this.lblFactura = lblFactura;
    }

    public JLabel getLblInicio() {
        return lblInicio;
    }

    public void setLblInicio(JLabel lblInicio) {
        this.lblInicio = lblInicio;
    }

    public JLabel getLblInventario() {
        return lblInventario;
    }

    public void setLblInventario(JLabel lblInventario) {
        this.lblInventario = lblInventario;
    }

    public JLabel getBtnMateriales() {
        return btnMateriales;
    }

    public void setBtnMateriales(JLabel btnMateriales) {
        this.btnMateriales = btnMateriales;
    }

    public JPanel getLblItems() {
        return lblItems;
    }

    public void setLblItems(JPanel lblItems) {
        this.lblItems = lblItems;
    }

    public JPanel getLblMotivoSoporte() {
        return lblMotivoSoporte;
    }

    public void setLblMotivoSoporte(JPanel lblMotivoSoporte) {
        this.lblMotivoSoporte = lblMotivoSoporte;
    }

    public JLabel getLblNombreUsuario() {
        return lblNombreUsuario;
    }

    public void setLblNombreUsuario(JLabel lblNombreUsuario) {
        this.lblNombreUsuario = lblNombreUsuario;
    }

    public JLabel getLblProvServiciosInternet() {
        return lblProvServiciosInternet;
    }

    public void setLblProvServiciosInternet(JLabel lblProvServiciosInternet) {
        this.lblProvServiciosInternet = lblProvServiciosInternet;
    }

    public JLabel getLblRegistroLlamadas() {
        return lblRegistroLlamadas;
    }

    public void setLblRegistroLlamadas(JLabel lblRegistroLlamadas) {
        this.lblRegistroLlamadas = lblRegistroLlamadas;
    }

    public JPanel getLblTarifaInstalacion() {
        return lblTarifaInstalacion;
    }

    public void setLblTarifaInstalacion(JPanel lblTarifaInstalacion) {
        this.lblTarifaInstalacion = lblTarifaInstalacion;
    }

    public JLabel getLblVentas() {
        return lblVentas;
    }

    public void setLblVentas(JLabel lblVentas) {
        this.lblVentas = lblVentas;
    }

    public JPanel getLbltipoCliente() {
        return lbltipoCliente;
    }

    /**
     * @param args the command line arguments
     */
    public void setLbltipoCliente(JPanel lbltipoCliente) {
        this.lbltipoCliente = lbltipoCliente;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicio2_0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicio2_0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicio2_0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicio2_0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicio2_0().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JPanel Panel1MenuInicio;
    private javax.swing.JPanel Panel2MenuInicio;
    private javax.swing.JLabel btnCasosSoporte;
    private javax.swing.JLabel btnContratos;
    private javax.swing.JLabel btnContribuyentes;
    private javax.swing.JLabel btnFacturas;
    private javax.swing.JLabel btnMateriales;
    private javax.swing.JLabel btnMotivosSoporte;
    private javax.swing.JLabel btnOrdenesTrabajo;
    private javax.swing.JLabel btnPlaneInternet;
    private javax.swing.JLabel btnReportes;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel btnSuspension;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel lblCasosSoporte;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JPanel lblContribuyentes;
    private javax.swing.JLabel lblDirectorio;
    private javax.swing.JPanel lblFactura;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblInventario;
    private javax.swing.JPanel lblItems;
    private javax.swing.JPanel lblMotivoSoporte;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblProvServiciosInternet;
    private javax.swing.JLabel lblRegistroLlamadas;
    private javax.swing.JPanel lblTarifaInstalacion;
    private javax.swing.JLabel lblVentas;
    private javax.swing.JPanel lbltipoCliente;
    private javax.swing.JPanel lbltipoContratos;
    private javax.swing.JPanel lbltipoOrdenes;
    // End of variables declaration//GEN-END:variables
}
