/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author aaron
 */
public class VentanaMateriales extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaMateriales
     */
    public VentanaMateriales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaContribuyente_PanelGeneral = new javax.swing.JPanel();
        VentanaContribuyentes_PanelBntNuevo = new javax.swing.JPanel();
        btnNuevoMaterial = new javax.swing.JButton();
        btnEditarMaterial = new javax.swing.JButton();
        btnAnularMaterial = new javax.swing.JButton();
        VentanaContribuyente_PanelContribuyente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        VentanaContribuyente_ComboActivo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarNombreMaterial = new javax.swing.JTextField();
        VentanaContribuyente_PanelAplicar = new javax.swing.JPanel();
        btnAplicarFiltrosMaterial = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnLimpiarFiltrosMaterial = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        VentanaContribuyente_TablaGeneral = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        VentanaContribuyente_PanelGeneral.setBackground(new java.awt.Color(255, 255, 255));
        VentanaContribuyente_PanelGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VentanaContribuyentes_PanelBntNuevo.setBackground(new java.awt.Color(204, 0, 0));

        btnNuevoMaterial.setBackground(new java.awt.Color(102, 102, 102));
        btnNuevoMaterial.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoMaterial.setText("Nuevo");

        btnEditarMaterial.setBackground(new java.awt.Color(102, 102, 102));
        btnEditarMaterial.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarMaterial.setText("Editar");

        btnAnularMaterial.setBackground(new java.awt.Color(102, 102, 102));
        btnAnularMaterial.setForeground(new java.awt.Color(255, 255, 255));
        btnAnularMaterial.setText("Anular");

        javax.swing.GroupLayout VentanaContribuyentes_PanelBntNuevoLayout = new javax.swing.GroupLayout(VentanaContribuyentes_PanelBntNuevo);
        VentanaContribuyentes_PanelBntNuevo.setLayout(VentanaContribuyentes_PanelBntNuevoLayout);
        VentanaContribuyentes_PanelBntNuevoLayout.setHorizontalGroup(
            VentanaContribuyentes_PanelBntNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaContribuyentes_PanelBntNuevoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnNuevoMaterial)
                .addGap(28, 28, 28)
                .addComponent(btnEditarMaterial)
                .addGap(18, 18, 18)
                .addComponent(btnAnularMaterial)
                .addContainerGap(724, Short.MAX_VALUE))
        );
        VentanaContribuyentes_PanelBntNuevoLayout.setVerticalGroup(
            VentanaContribuyentes_PanelBntNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaContribuyentes_PanelBntNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VentanaContribuyentes_PanelBntNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarMaterial)
                    .addComponent(btnNuevoMaterial)
                    .addComponent(btnAnularMaterial))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        VentanaContribuyente_PanelGeneral.add(VentanaContribuyentes_PanelBntNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 980, 50));

        VentanaContribuyente_PanelContribuyente.setBackground(new java.awt.Color(255, 255, 255));
        VentanaContribuyente_PanelContribuyente.setBorder(javax.swing.BorderFactory.createTitledBorder("Materiales"));
        VentanaContribuyente_PanelContribuyente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Activo(a):");
        VentanaContribuyente_PanelContribuyente.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 21, -1, -1));

        VentanaContribuyente_ComboActivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO FILTRAR", "SI", "NO" }));
        VentanaContribuyente_PanelContribuyente.add(VentanaContribuyente_ComboActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 159, -1));

        jLabel2.setText("Nombre material:");
        VentanaContribuyente_PanelContribuyente.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));
        VentanaContribuyente_PanelContribuyente.add(txtBuscarNombreMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 220, -1));

        VentanaContribuyente_PanelGeneral.add(VentanaContribuyente_PanelContribuyente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 980, 100));

        VentanaContribuyente_PanelAplicar.setBackground(new java.awt.Color(204, 0, 0));

        btnAplicarFiltrosMaterial.setBackground(new java.awt.Color(102, 102, 102));
        btnAplicarFiltrosMaterial.setForeground(new java.awt.Color(255, 255, 255));
        btnAplicarFiltrosMaterial.setText("Aplicar Filtros");

        btnActualizar.setBackground(new java.awt.Color(102, 102, 102));
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");

        btnLimpiarFiltrosMaterial.setBackground(new java.awt.Color(102, 102, 102));
        btnLimpiarFiltrosMaterial.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarFiltrosMaterial.setText("Restablecer Filtros");

        javax.swing.GroupLayout VentanaContribuyente_PanelAplicarLayout = new javax.swing.GroupLayout(VentanaContribuyente_PanelAplicar);
        VentanaContribuyente_PanelAplicar.setLayout(VentanaContribuyente_PanelAplicarLayout);
        VentanaContribuyente_PanelAplicarLayout.setHorizontalGroup(
            VentanaContribuyente_PanelAplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaContribuyente_PanelAplicarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAplicarFiltrosMaterial)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarFiltrosMaterial)
                .addContainerGap(606, Short.MAX_VALUE))
        );
        VentanaContribuyente_PanelAplicarLayout.setVerticalGroup(
            VentanaContribuyente_PanelAplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaContribuyente_PanelAplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnAplicarFiltrosMaterial)
                .addComponent(btnActualizar)
                .addComponent(btnLimpiarFiltrosMaterial))
        );

        VentanaContribuyente_PanelGeneral.add(VentanaContribuyente_PanelAplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 980, 40));

        VentanaContribuyente_TablaGeneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre Material", "Existencias", "Creado por", "Fecha de Creacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(VentanaContribuyente_TablaGeneral);

        VentanaContribuyente_PanelGeneral.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 980, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaContribuyente_PanelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaContribuyente_PanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMateriales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMateriales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMateriales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMateriales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMateriales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> VentanaContribuyente_ComboActivo;
    private javax.swing.JPanel VentanaContribuyente_PanelAplicar;
    private javax.swing.JPanel VentanaContribuyente_PanelContribuyente;
    private javax.swing.JPanel VentanaContribuyente_PanelGeneral;
    private javax.swing.JTable VentanaContribuyente_TablaGeneral;
    private javax.swing.JPanel VentanaContribuyentes_PanelBntNuevo;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAnularMaterial;
    private javax.swing.JButton btnAplicarFiltrosMaterial;
    private javax.swing.JButton btnEditarMaterial;
    private javax.swing.JButton btnLimpiarFiltrosMaterial;
    private javax.swing.JButton btnNuevoMaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscarNombreMaterial;
    // End of variables declaration//GEN-END:variables
}
